### ISSUE TITLE
ADFS Integration

### ISSUE THREAD

**Issue by avenmia** [acm-uic/PassiveApi#2]
- [x] Retrieve claims from SAML Response
- [x] Decode SAML Response
- [ ] Authorize user based on group memberships

**Comment by bmiddha** [comment]
# Application Privleges
The application needs to have have 2 privilege levels: Admin, User.
Admins:  memberOf attribute of **ACMLanAdmins** or **ACMOfficers**
Users: memberOf attribute of **ACMPaid** or is an Admin
A User can update their own details (only some attributes such as Name, Phone Number, Email, etc.)
An Admin can update other user's details.
Every Admin is also a User, therefore they can update their own details.

**Comment by avenmia** [comment]
Authorize user based on group memberships will be part of the basic api not the adfs integration #4
